#!/usr/bin/env bash
set -euo pipefail

# restore custom-compiled emacs

SCRIPT_NAME="${BASH_SOURCE[0]##*/}"
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

usage() {
    cat <<-EOU
usage: ${SCRIPT_NAME} [--help] | [SRCDIR] [EMACSFLAVOR]

Installs Emacs from SRCDIR and registers it as EMACSFLAVOR with the Debian
Emacs infrastructure provided by the emacsen-common package.

Options:
    -h, --help
        show this message
    SRCDIR:
        Emacs source directory (default: current directory)
    EMACSFLAVOR
        name (aka flavor) of the installed Emacs (default: emacs-snapshot)
EOU
}

DEB_PACKAGE="emacs-snapshot_1.0_all.deb"
_emacs_marker='lisp/startup.el'

EMACS_SRC_DIR="${PWD}"
EMACS_FLAVOR="emacs-snapshot"
while [ ${#} -gt 0 ]; do
    case "${1}" in
        -h | -\? | --help)
            usage
            exit 0
            ;;
        -*)
            echo "[ERR] unsupported option: ${1@Q}"
            echo
            usage
            exit 1
            ;;
        *)
            if [ -f "${1:-}/${_emacs_marker}" ]; then
                cd "${1%/}"
                EMACS_SRC_DIR="${PWD}"
            else
                EMACS_FLAVOR="${1}"
            fi
            ;;
    esac
    shift
done

[ -f "${EMACS_SRC_DIR}/${_emacs_marker}" ] || {
    echo "[ERR] ${PWD@Q} is not an Emacs source tree"
    echo
    usage
    exit 1
}

[ "${EUID}" = "0" ] || {
    if command -v sudo &>/dev/null; then
        echo "[INF] You must be root to run this, restarting with sudo ..."
        exec sudo JOB_COUNT="${JOB_COUNT-}" \
             "${SCRIPT_DIR}/${SCRIPT_NAME}" "${EMACS_SRC_DIR}" "${EMACS_FLAVOR}"
    else
        echo "[ERR] You must be root to run this."
        exit 1
    fi
}

SRC_SHARE_DIR="/usr/local/share/emacs"
DST_SHARE_DIR="/usr/share/${EMACS_FLAVOR}"

echo "[INF] Stage 1: Use 'make' to build/install Emacs from source tree ..."
# remove potential (dangling?) symlink
if [ -L "${SRC_SHARE_DIR}/site-lisp" ] &&
       [ "$(realpath "${SRC_SHARE_DIR}/site-lisp")" != "${DST_SHARE_DIR}/site-lisp" ]; then
    rm -v "${SRC_SHARE_DIR}/site-lisp"
fi
if [ -n "${SUDO_USER}" ]; then
    # When running under sudo, build Emacs as original user to avoid creating
    # build artefacts as superuser.
    #
    # Unfortunately, `make --question` doesn't work with the Emacs build system,
    # otherwise we could check if a (re-)build is required.
    [ -v JOB_COUNT ] || JOB_COUNT="$(($(nproc 2>/dev/null || echo 0) + 1))"
    sudo -u "${SUDO_USER}" make "${JOB_COUNT:+--jobs=${JOB_COUNT}}"
fi
make install
VERSION="$(realpath /usr/local/bin/emacs | cut -d'-' -f2)"
echo "[INF] Stage 1: Done."
echo

echo "[INF] Stage 2: Install dummy ${DEB_PACKAGE} package ..."
dpkg -i "${SCRIPT_DIR}/${DEB_PACKAGE}"
echo "[INF] Stage 2: Done."
echo

echo "[INF] Stage 3: Prepare Emacs ${VERSION} flavorization as ${EMACS_FLAVOR@Q} ..."
# This stage of restore-emacs tries to integrate the newly installed Emacs with
# the Debian Emacs infrastructure provided by the `emacsen-common` package.
#
# The Debian package `emacsen-common` provides infrastructure which facilitates
# the interworking between Emacs flavors (main Emacs packages providing the
# actual binaries) and Emacs add-on packages (e.g. elisp libraries). The
# `emacsen-common` package provides a description of how to use this
# infrastructure in `/usr/share/doc/emacsen-common/debian-emacs-policy.gz`.
#
# The `emacsen-common` scripts register installed emacsen by creating the
# `/var/lib/emacsen-common/state/flavor/<emacs-flavor>` file. This is then used
# to make sure that each installed 'flavored' Emacs will 'see' installed elisp
# packages. That process is managed by a couple of scripts in
# `/usr/lib/emacsen-common/`.
#
# Debian elisp packages install .el files into `/usr/share/<package-name>/`.
# The above mentioned `emacsen-common` scripts then install symbolic links to
# these elisp files into `/usr/share/<emacs-flavor>/site-lisp/`. Unfortunately,
# some of these symlinks are relative. So just creating a symbolic link from
# `/usr/share/<emacs-flavor>` to `/usr/local/share/emacs` directory is not an
# option.
#
# See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840793.
#
# As a workaround, create `/usr/share/<emacs-flavor>` as a directory and move
# `/usr/local/share/emacs/site-lisp` to it. Then recreate
# `/usr/local/share/emacs/site-lisp` as a symlink to
# `/usr/share/<emacs-flavor>/site-lisp`.

if [ -L "${DST_SHARE_DIR}" ]; then
    rm -v "${DST_SHARE_DIR}" # just a symlink, should be save to remove
fi
mkdir -pv "${DST_SHARE_DIR}"

# exit with an error check if the (potentially) existing symlink is not what we
# expect or, if there is no symlink, do the shuffle described above
if [ -L "${SRC_SHARE_DIR}/site-lisp" ]; then
    if [ "$(realpath "${SRC_SHARE_DIR}/site-lisp")" != "${DST_SHARE_DIR}/site-lisp" ]; then
        echo "[ERR] unexpected link target of '${SRC_SHARE_DIR}/site-lisp', expected"
        echo "[ERR] '${DST_SHARE_DIR}/site-lisp', found '$(realpath "${SRC_SHARE_DIR}/site-lisp")'"
        echo "[ERR] please check!"
        exit 2
    fi
else
    # move common site-lisp directory to /usr/share/<emacs-flavor>/
    mv -v "${SRC_SHARE_DIR}/site-lisp" "${DST_SHARE_DIR}/"
    # and replace its original location with a symlink to the moved directory
    ln -sfnv "${DST_SHARE_DIR}/site-lisp" "${SRC_SHARE_DIR}/"
fi

# link versioned emacs installation directory into /usr/share/<emacs-flavor>/
# (not necessary, but helps understanding where /usr/share/<emacs-flavor>/
# originates from)
ln -sfnv "${SRC_SHARE_DIR}/${VERSION}" "${DST_SHARE_DIR}/"

# remove `debian-startup.el` installed using the instructions from a previous
# version of this project
if [ -f "${SRC_SHARE_DIR}/${VERSION}/site-lisp/debian-startup.el" ]; then
    rm -fv "${SRC_SHARE_DIR}/${VERSION}/site-lisp/debian-startup".*
fi

# create am ${EMACS_FLAVOR} link in /usr/bin/ which targets the (versioned)
# emacs binary in /usr/local/bin (see debian-emacs-policy section 6)
ln -sfv "$(realpath "/usr/local/bin/emacs")" "/usr/bin/${EMACS_FLAVOR}"

# symlink /etc/<emacs-flavor> to the /etc/emacs directory to allow
# '/usr/share/<emacs-flavor>/site-lisp/debian-startup.el' (another part of
# `emacsen-common`) to do its work
if [ -L "/etc/${EMACS_FLAVOR}" ]; then
    # check for and allow 'legacy' directory structure, but exit if current
    # directory structure is different from what is required
    if [ "$(realpath "/etc/${EMACS_FLAVOR}")" != "/etc/emacs" ]; then
        echo "[ERR] unexpected link target of '${SRC_SHARE_DIR}/site-lisp', expected"
        echo "[ERR] '${DST_SHARE_DIR}/site-lisp', found '$(realpath "${SRC_SHARE_DIR}/site-lisp")'"
        echo "[ERR] please check!"
        exit 3
    fi
elif [ -d "/etc/${EMACS_FLAVOR}" ]; then
    if [ "$(realpath "/etc/${EMACS_FLAVOR}/site-start.d")" != "/etc/emacs/site-start.d" ]; then
        echo "[ERR] '/etc/${EMACS_FLAVOR}' should be a symlink to '/etc/emacs', please check"
        exit 4
    fi
else
    ln -sf "emacs" "/etc/${EMACS_FLAVOR}"
fi
echo "[INF] Stage 3: Done."
echo

echo "[INF] Stage 4: Register/initialize Emacs flavor ${EMACS_FLAVOR@Q} ..."
# run the Debian 'emacs-install' script to a) register the newly installed
# ${EMACS_FLAVOR} with `emacsen-common` and b) add already installed elisp
# packages to /usr/share/<emacs-flavor>/site-lisp.
/usr/lib/emacsen-common/emacs-install "${EMACS_FLAVOR}"
echo "[INF] Stage 4: Done."
echo

DST_SITE_START="/usr/local/share/emacs/${VERSION}/site-lisp/site-start.el"
echo "[INF] Stage 5: Install/update ${DST_SITE_START@Q} ..."
# copy the local site-start.el to /usr/local/share/emacs/<version>/site-lisp in
# order to load '/usr/share/<emacs-flavor>/site-lisp/debian-startup.el' and run
# the elisp `debian-startup' function during Emacs startup
install --mode 644 --verbose "${SCRIPT_DIR}/site-start.el" "${DST_SITE_START}"
# update `debian-emacs-flavor'
sed -i -E "s,emacs-snapshot,${EMACS_FLAVOR}," "${DST_SITE_START}"
echo "[INF] Stage 5: Done."
echo

echo "[INF] ${SCRIPT_NAME} finished successfully!"
