#!/bin/bash
#
# Restore custom-compiled emacs

if test ! -d ./lisp/emacs-lisp; then
    echo "You are not in the right directory."
    exit 1
fi

if test "$UID" != "0"; then
    echo "You must be root to run this."
    exit 1
fi

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

echo "Stage 1: Installing emacs ..."
make install
VERSION="$(realpath /usr/local/bin/emacs | cut -d'-' -f2)"

echo "Stage 2: Install fake emacs-snapshot package ..."
dpkg -i "${SCRIPT_DIR}/emacs-snapshot_1.0_all.deb"

echo "Done."
echo "Stage 3: Making symlinks ..."
ln -sfn "/usr/local/share/emacs/${VERSION}" /usr/share/emacs-snapshot
ln -sf /usr/local/bin/emacs /usr/bin/emacs-snapshot
mkdir -p /etc/emacs-snapshot/
ln -sf /etc/emacs/site-start.d /etc/emacs-snapshot/

echo "Done."
echo "Stage 4: Installing emacs-snapshot flavor ..."
/usr/lib/emacsen-common/emacs-install emacs-snapshot

echo "Done."
